version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 selhub:
  build: ./Hub
  ports:
   - 4444:4444
  networks: 
   - prodnetwork

 nodeff4402debug:
  image: selenium/node-firefox-4402
  networks: 
   - prodnetwork
  environment:
   - HUB_PORT_4444_TCP_ADDR=selhub
  ports:
   - 5920:5900
  depends_on:
   - selhub

 nodeff4502debug:
  image: selenium/node-firefox-4502
  networks: 
   - prodnetwork
  environment:
   - HUB_PORT_4444_TCP_ADDR=selhub
  ports:
   - 5921:5900
  depends_on:
   - selhub


 nodeff4601debug:
  image: selenium/node-firefox-4601
  networks: 
   - prodnetwork
  environment:
   - HUB_PORT_4444_TCP_ADDR=selhub
  ports:
   - 5922:5900
  depends_on:
   - selhub


